import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from './provider'

import * as Sentry from '@sentry/nextjs';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Zakarias portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}><ThemeProvider
        attribute="class"
        defaultTheme="dark"
        enableSystem
        disableTransitionOnChange
      >
        {children}</ThemeProvider></body>
    </html>
  )
}



//// Add or edit your "generateMetadata" to include the Sentry trace data:
//export function generateMetadata(): Metadata {
//  return {
//    // ... your existing metadata
//    other: {
//      ...Sentry.getTraceData()
//    }
//  };
//}